packages:
  - 'packages/*'
  - 'examples/*'
  - 'apps/*'
overrides:
  sharp: '^0.35.0'
  brace-expansion: '^2.1.4'
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false
  sharp: true
minimumReleaseAgeExclude:
  - '@astrojs/starlight@0.41.5'
