export const DEFAULT_TRANSITION_DURATION = 300

export const DEFAULT_TRANSITION_EASING = 'cubic-bezier(0.22, 1, 0.36, 1)'

export const TRANSITION_EPSILON = 0.5

export const TRANSITION_ENTER_RISE = 12

export const DEFAULT_REACH_END_THRESHOLD = 200
